import { MonsterDef } from '../types';

const monsters: MonsterDef[] = [
  // ── COMMON (IDs 0-9) ──
  { id: 0, name: 'Fire Lizard', rarity: 'common', element: 'Fire', hp: 95, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Ember Bite', damage: 18, description: 'Bites with flaming jaws.' }, { name: 'Tail Whip', damage: 25, description: 'Lashes with a burning tail.' }],
    spriteSheet: 1, spriteRow: 0, spriteCol: 0, description: 'A small lizard wreathed in fire.' },
  { id: 1, name: 'Bubble Frog', rarity: 'common', element: 'Water', hp: 88, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Bubble Shot', damage: 15, description: 'Fires a burst of soap bubbles.' }, { name: 'Slime Splash', damage: 22, description: 'Drenches the foe in sticky slime.' }],
    spriteSheet: 1, spriteRow: 0, spriteCol: 1, description: 'A cheerful frog that blows magical bubbles.' },
  { id: 2, name: 'Blossom Bird', rarity: 'common', element: 'Nature', hp: 82, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Petal Gust', damage: 14, description: 'Whips up a storm of petals.' }, { name: 'Wing Slash', damage: 24, description: 'Strikes with razor-sharp wings.' }],
    spriteSheet: 1, spriteRow: 0, spriteCol: 2, description: 'A colorful bird with flower-patterned feathers.' },
  { id: 3, name: 'Spark Mouse', rarity: 'common', element: 'Electric', hp: 80, maxCopies: 3, fragmentValue: 15,
    skills: [
      { name: 'Zap Bite', damage: 16, description: 'Bites while releasing sparks.', isElectric: true },
      { name: 'Thunder Gamble', damage: 0, description: 'Flip 3 coins — +15 per Heads. All 3: +45 bonus!', isElectric: true, coinToss: { count: 3, damagePerHead: 15, allHeadsBonus: 45 } },
    ],
    spriteSheet: 1, spriteRow: 0, spriteCol: 3, description: 'An energetic mouse crackling with static electricity.' },
  { id: 4, name: 'Stone Turtle', rarity: 'common', element: 'Earth', hp: 110, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Shell Bash', damage: 12, description: 'Charges with its heavy shell.' }, { name: 'Rock Toss', damage: 20, description: 'Hurls a chunk of stone.' }],
    spriteSheet: 1, spriteRow: 0, spriteCol: 4, description: 'A slow but durable turtle with a rock-solid shell.' },
  { id: 5, name: 'Mystic Cat', rarity: 'common', element: 'Mystic', hp: 85, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Shadow Claw', damage: 20, description: 'Strikes from the shadows.' }, { name: 'Mystic Pulse', damage: 28, description: 'Releases a wave of arcane energy.' }],
    passive: { description: '9% chance to dodge incoming attacks.', type: 'dodge', value: 9 },
    spriteSheet: 1, spriteRow: 0, spriteCol: 5, description: 'A mysterious cat with glowing eyes.' },
  { id: 6, name: 'Beetle Knight', rarity: 'common', element: 'Earth', hp: 100, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Horn Thrust', damage: 17, description: 'Drives its horn into the foe.' }, { name: 'Armor Charge', damage: 22, description: 'Charges headfirst with its shell.' }],
    passive: { description: 'After taking damage, gain 5 HP armor.', type: 'armor', value: 5 },
    spriteSheet: 1, spriteRow: 0, spriteCol: 6, description: 'A beetle clad in natural armor.' },
  { id: 7, name: 'Little Devil', rarity: 'common', element: 'Fire', hp: 90, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Cinder Toss', damage: 19, description: 'Hurls a burning ember.' }, { name: 'Devil Scratch', damage: 27, description: 'Rakes with devilish claws.' }],
    spriteSheet: 1, spriteRow: 0, spriteCol: 7, description: 'A tiny devil with a mischievous grin.' },
  { id: 8, name: 'Crystal Wolf', rarity: 'common', element: 'Ice', hp: 92, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Crystal Fang', damage: 21, description: 'Bites with gemstone-hard teeth.' }, { name: 'Shard Howl', damage: 28, description: 'Fires crystal shards in a howl.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 0, description: 'A wolf covered in ice crystals.' },
  { id: 9, name: 'Pink Chick', rarity: 'common', element: 'Light', hp: 80, maxCopies: 3, fragmentValue: 15,
    skills: [{ name: 'Peck', damage: 10, description: 'A quick, sharp peck.' }, { name: 'Cute Gaze', damage: 18, description: 'A disarming stare.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 1, description: 'An adorable pink chick.' },

  // ── RARE (IDs 10-19) ──
  { id: 10, name: 'Hedgehog', rarity: 'rare', element: 'Earth', hp: 130, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Spine Barrage', damage: 28, description: 'Launches a volley of spines.' }, { name: 'Roll Charge', damage: 40, description: 'Curls into a ball and rams.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 2, description: 'A spiky hedgehog whose quills pierce any armor.' },
  { id: 11, name: 'Thunder Sheep', rarity: 'rare', element: 'Electric', hp: 125, maxCopies: 2, fragmentValue: 40,
    skills: [
      { name: 'Static Wool', damage: 25, description: 'Releases electricity from its coat.', isElectric: true },
      { name: 'Electric Storm', damage: 0, description: 'Flip 2 coins — Heads: 25 dmg each, Tails: 0.', isElectric: true, coinToss: { count: 2, damagePerHead: 25, allHeadsBonus: 0, tailsDamage: 0 } },
    ],
    spriteSheet: 1, spriteRow: 1, spriteCol: 3, description: 'A woolly sheep charged with lightning.' },
  { id: 12, name: 'Moss Golem', rarity: 'rare', element: 'Nature', hp: 160, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Ground Slam', damage: 30, description: 'Slams both fists into the ground.' }, { name: 'Vine Whip', damage: 38, description: 'Lashes out with living vines.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 4, description: 'A massive golem of living moss and stone.' },
  { id: 13, name: 'Spirit Dog', rarity: 'rare', element: 'Light', hp: 135, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Phantom Bite', damage: 32, description: 'Bites with spectral fangs.' }, { name: 'Howl of Souls', damage: 42, description: 'A ghostly howl.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 5, description: 'A ghostly white dog with a spectral aura.' },
  { id: 14, name: 'Jungle Snake', rarity: 'rare', element: 'Nature', hp: 128, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Venom Fang', damage: 29, description: 'Injects potent venom.' }, { name: 'Constrict', damage: 43, description: 'Wraps around and squeezes.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 6, description: 'A sleek jungle serpent with paralyzing venom.' },
  { id: 15, name: 'Iron Armadillo', rarity: 'rare', element: 'Steel', hp: 155, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Iron Roll', damage: 26, description: 'Rolls at high speed in a metal ball.' }, { name: 'Claw Slash', damage: 37, description: 'Tears with iron-hard claws.' }],
    spriteSheet: 1, spriteRow: 1, spriteCol: 7, description: 'An armadillo with plating harder than steel.' },
  { id: 16, name: 'Ice Fox', rarity: 'rare', element: 'Ice', hp: 132, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Frost Bite', damage: 33, description: 'Bites, leaving frost.' }, { name: 'Blizzard Tail', damage: 44, description: 'Whips up a localized blizzard.' }],
    spriteSheet: 1, spriteRow: 2, spriteCol: 0, description: 'A graceful fox of ice and snow.' },
  { id: 17, name: 'Sky Eagle', rarity: 'rare', element: 'Wind', hp: 120, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Talon Strike', damage: 35, description: 'Dives and slashes with sharp talons.' }, { name: 'Gale Wing', damage: 45, description: 'Beats wings with hurricane force.' }],
    passive: { description: '15% chance to strike twice in one turn.', type: 'double_attack', value: 15 },
    spriteSheet: 1, spriteRow: 2, spriteCol: 1, description: 'A majestic eagle that rides storm winds.' },
  { id: 18, name: 'Nature Bear', rarity: 'rare', element: 'Nature', hp: 150, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Bear Claw', damage: 31, description: 'Swipes with nature-attuned claws.' }, { name: 'Forest Roar', damage: 41, description: 'A roar that shakes the trees.' }],
    passive: { description: 'Recover 10 HP every 2 turns.', type: 'regen', value: 10, triggerCondition: 'every_2_turns' },
    spriteSheet: 1, spriteRow: 2, spriteCol: 2, description: 'A bear blessed by the forest.' },
  { id: 19, name: 'Floating Eye', rarity: 'rare', element: 'Mystic', hp: 122, maxCopies: 2, fragmentValue: 40,
    skills: [{ name: 'Evil Gaze', damage: 34, description: 'A petrifying stare.' }, { name: 'Psychic Burst', damage: 43, description: 'Unleashes a wave of psychic energy.' }],
    spriteSheet: 1, spriteRow: 2, spriteCol: 3, description: 'A disembodied eye that drifts silently.' },

  // ── LEGENDARY (IDs 20-29) ──
  { id: 20, name: 'Shadow Beetle', rarity: 'legendary', element: 'Dark', hp: 185, maxCopies: 1, fragmentValue: 120,
    skills: [
      { name: 'Shadow Crush', damage: 48, description: 'Crushes with darkness-infused pincers.' },
      { name: 'Dark Fortune', damage: 0, description: 'Flip 4 coins — 20 per Heads. All 4: +60!', coinToss: { count: 4, damagePerHead: 20, allHeadsBonus: 60 } },
    ],
    spriteSheet: 1, spriteRow: 2, spriteCol: 4, description: 'A colossal beetle infused with shadow energy.' },
  { id: 21, name: 'Lantern Angler', rarity: 'legendary', element: 'Water', hp: 190, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Lure Strike', damage: 45, description: 'Lures and strikes from below.' }, { name: 'Abyss Bite', damage: 65, description: 'Bites with the fury of the deep.' }],
    spriteSheet: 1, spriteRow: 2, spriteCol: 5, description: 'An anglerfish whose lantern mesmerizes prey.' },
  { id: 22, name: 'Rock Crocodile', rarity: 'legendary', element: 'Earth', hp: 210, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Stone Snap', damage: 50, description: 'Snaps jaws with crushing rock force.' }, { name: 'Earthquake Tail', damage: 63, description: 'Slams tail causing a quake.' }],
    spriteSheet: 1, spriteRow: 2, spriteCol: 6, description: 'A prehistoric crocodile whose scales are living stone.' },
  { id: 23, name: 'Wind Serpent', rarity: 'legendary', element: 'Wind', hp: 175, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Cyclone Bite', damage: 47, description: 'Bites while spinning like a tornado.' }, { name: 'Air Lance', damage: 62, description: 'Fires a compressed lance of wind.' }],
    passive: { description: '10% chance to avoid incoming damage.', type: 'dodge', value: 10 },
    spriteSheet: 1, spriteRow: 2, spriteCol: 7, description: 'A serpent made of living wind.' },
  { id: 24, name: 'Lava Slime', rarity: 'legendary', element: 'Fire', hp: 180, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Magma Blob', damage: 44, description: 'Hurls a glob of molten rock.' }, { name: 'Eruption', damage: 66, description: 'Explodes in a volcanic eruption.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 0, description: 'A slime born in a volcano.' },
  { id: 25, name: 'Coral Beast', rarity: 'legendary', element: 'Water', hp: 195, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Coral Spike', damage: 46, description: 'Fires razor-sharp coral shards.' }, { name: 'Reef Crush', damage: 60, description: 'Smashes with a living coral fist.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 1, description: 'A beast made of living coral.' },
  { id: 26, name: 'Magma Salamander', rarity: 'legendary', element: 'Fire', hp: 188, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Flame Lick', damage: 50, description: 'Licks with a tongue of pure fire.' }, { name: 'Magma Dive', damage: 64, description: 'Dives into magma and resurfaces.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 2, description: 'A salamander that swims in magma.' },
  { id: 27, name: 'Storm Hawk', rarity: 'legendary', element: 'Wind', hp: 172, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Thunder Dive', damage: 53, description: 'Dives at lightning speed.' }, { name: 'Storm Shriek', damage: 68, description: 'Releases a thunderclap shockwave.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 3, description: 'A hawk born in a thunderstorm.' },
  { id: 28, name: 'Shadow Wraith', rarity: 'legendary', element: 'Dark', hp: 178, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Wraith Slash', damage: 52, description: 'Cuts with a blade of shadow.' }, { name: 'Soul Drain', damage: 58, description: 'Drains the life force of the foe.' }],
    passive: { description: 'Steal 25% of damage dealt as HP.', type: 'lifesteal', value: 25 },
    spriteSheet: 1, spriteRow: 3, spriteCol: 4, description: 'A wraith that feeds on souls.' },
  { id: 29, name: 'Crystal Crab', rarity: 'legendary', element: 'Ice', hp: 220, maxCopies: 1, fragmentValue: 120,
    skills: [{ name: 'Crystal Pinch', damage: 42, description: 'Clamps with crystalline claws.' }, { name: 'Prism Blast', damage: 60, description: 'Fires a rainbow beam from its shell.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 5, description: 'A crab with a shell of prismatic crystals.' },

  // ── MYTHICAL (IDs 30-39) ──
  { id: 30, name: 'Ice Titan', rarity: 'mythical', element: 'Ice', hp: 270, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Glacial Fist', damage: 65, description: 'A punch wrapped in absolute zero.' }, { name: 'Permafrost', damage: 88, description: 'Freezes the battlefield solid.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 6, description: 'A titan carved from eternal ice.' },
  { id: 31, name: 'Forest Deer', rarity: 'mythical', element: 'Nature', hp: 245, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Antler Charge', damage: 60, description: 'Charges with glowing antlers.' }, { name: "Nature's Wrath", damage: 90, description: 'Summons vines and thorns.' }],
    spriteSheet: 1, spriteRow: 3, spriteCol: 7, description: 'A divine deer wreathed in living vines.' },
  { id: 32, name: 'Moon Moth', rarity: 'mythical', element: 'Light', hp: 235, maxCopies: 1, fragmentValue: 300,
    skills: [
      { name: 'Stardust', damage: 55, description: 'Showers the foe in cosmic dust.' },
      { name: 'Lunar Destiny', damage: 0, description: 'Flip 1 coin — Heads: 80 dmg, Tails: 20 dmg.', coinToss: { count: 1, damagePerHead: 80, allHeadsBonus: 0, tailsDamage: 20 } },
    ],
    spriteSheet: 1, spriteRow: 4, spriteCol: 0, description: 'A moth born from moonlight.' },
  { id: 33, name: 'Toxic Frog', rarity: 'mythical', element: 'Nature', hp: 240, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Poison Nova', damage: 62, description: 'Releases a cloud of lethal toxins.' }, { name: 'Acid Torrent', damage: 92, description: 'Unleashes a torrent of dissolving acid.' }],
    spriteSheet: 1, spriteRow: 4, spriteCol: 1, description: 'A giant frog dripping with the most potent poison.' },
  { id: 34, name: 'Ancient Golem', rarity: 'mythical', element: 'Earth', hp: 300, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Titan Stomp', damage: 58, description: 'Stomps, creating a shockwave.' }, { name: 'Ruin Strike', damage: 85, description: 'Strikes with the force of a mountain.' }],
    spriteSheet: 1, spriteRow: 4, spriteCol: 2, description: 'A golem built by an ancient civilization.' },
  { id: 35, name: 'Thunder Robot', rarity: 'mythical', element: 'Electric', hp: 255, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Bolt Cannon', damage: 65, description: 'Fires a concentrated lightning bolt. +20 bonus.', isElectric: true }, { name: 'Overcharge', damage: 78, description: 'Overloads circuits for a massive blast. +20 bonus.', isElectric: true }],
    passive: { description: 'All electric skills deal +20 bonus damage.', type: 'electric_boost', value: 20 },
    spriteSheet: 1, spriteRow: 4, spriteCol: 3, description: 'A robot powered by captured lightning.' },
  { id: 36, name: 'Dark Bat', rarity: 'mythical', element: 'Dark', hp: 238, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Void Screech', damage: 60, description: 'A screech that tears through reality.' }, { name: 'Nightmare Dive', damage: 95, description: 'Dives from the void.' }],
    spriteSheet: 1, spriteRow: 4, spriteCol: 4, description: 'A bat that flies through the void between dimensions.' },
  { id: 37, name: 'Elder Jellyfish', rarity: 'mythical', element: 'Water', hp: 250, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Neuro Sting', damage: 63, description: 'Stings with paralytic venom.' }, { name: 'Deep Pulse', damage: 88, description: 'Sends a crushing pulse from the deep.' }],
    spriteSheet: 1, spriteRow: 4, spriteCol: 5, description: 'An ancient jellyfish from the deepest ocean trench.' },
  { id: 38, name: 'Bone Vulture', rarity: 'mythical', element: 'Dark', hp: 242, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Death Talon', damage: 67, description: 'Slashes with bone-white talons.' }, { name: 'Carrion Storm', damage: 93, description: 'Summons a storm of bone shards.' }],
    spriteSheet: 1, spriteRow: 4, spriteCol: 6, description: 'A vulture of bones and death omens.' },
  { id: 39, name: 'Golden Bull', rarity: 'mythical', element: 'Earth', hp: 280, maxCopies: 1, fragmentValue: 300,
    skills: [{ name: 'Gold Rush', damage: 58, description: 'Charges with its golden horns.' }, { name: 'Bull Rage', damage: 82, description: 'Unleashes a furious golden rampage.' }],
    passive: { description: 'When HP drops below 50%, damage increases by 25%.', type: 'damage_boost', value: 25, triggerCondition: 'low_hp' },
    spriteSheet: 1, spriteRow: 4, spriteCol: 7, description: 'A legendary bull plated in pure gold.' },
];

export default monsters;
export function getMonsterById(id: number): MonsterDef | undefined { return monsters.find(m => m.id === id); }
